baseURL: "https://aminabyaneh.github.io/"
title: Amin Abyaneh
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags
# we have to fix the menu

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        # - name: Projects # TODO: add projects later
        #   url: projects/
        #   weight: 2
        - name: Blog
          url: blog/
          weight: 3

params:
    description: "This website hosts Amin Abyaneh's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Amin Abyaneh
    googleAnalyticsID: "G-LE3F13RMP1" # TODO: change later
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers", "blog"] # TODO: add projects later
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Amin Abyaneh
          subtitle: "I am a PhD candidate in AI and Robotics at McGill University and Mila. My research focuses on physical intelligence through learning dynamical systems to enable sequential decision making with data-driven models. I study how agents can build internal world models that capture the structure and evolution of their environments, enabling prediction, planning, and control under uncertainty. By bridging dynamical systems, probabilistic modeling, and modern generative methods, I aim to develop principled learning algorithms that scale to real-world decision-making problems."
          imageUrl: "avatar.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Projects
              url: projects/
            - name: Blog
              url: blog/

    socialIcons:
        - name: Email
          url: mailto:amin.abyaneh@mail.mcgill.ca
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=Hq0AYv8AAAAJ&hl=en
        - name: GitHub
          url: https://github.com/aminabyaneh
        - name: LinkedIn
          url: https://www.linkedin.com/in/amin-abyaneh-02a255123/


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Amin Abyaneh"
      icon: icon.png
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
